### ISSUE TITLE
叩くAPI 選定

### ISSUE THREAD

**Issue by ia17011** [GitHub0rganization/linqs#2]
## 行うこと
- 叩く外部API選定
### 選びもの
- 本
- 映画
- 漫画

**Comment by tomu28** [comment]
本は、楽天が良さげ

**Comment by tomu28** [comment]
音楽は、Spotifyだと再生も可能

[参考](https://dev.classmethod.jp/etc/play-music-via-spotify-web-api/)

**Comment by tomu28** [comment]
映画は要検討

https://medium.com/@mmmatch/%E6%88%A6%E4%BA%89%E6%98%A0%E7%94%BB%E3%81%AE%E3%82%B5%E3%82%A4%E3%83%88%E3%82%92%E4%BD%9C%E3%81%A3%E3%81%9F%E8%A9%B1-%E3%81%9D%E3%81%AE%EF%BC%93-62511b7541df
